# Generated by Django 5.2.6 on 2025-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportsPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "permissions": (
                    ("view_reports", "Can view reports dashboard"),
                    ("view_detailed_reports", "Can view detailed reports"),
                    ("export_reports", "Can export reports"),
                ),
            },
        ),
    ]
