# Generated by Django 5.2.6 on 2025-09-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=100)),
                ("machine_code", models.CharField(max_length=100)),
                ("machine_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rated_output",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rated output in bottles per hour",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
            },
        ),
        migrations.CreateModel(
            name="PackageSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                (
                    "package_type",
                    models.CharField(
                        choices=[("PET", "PET Bottle"), ("CAN", "Can")], max_length=10
                    ),
                ),
                (
                    "volume_ml",
                    models.PositiveIntegerField(
                        default=500, help_text="Volume in milliliters"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                (
                    "standard_syrup_ratio",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="Standard syrup ratio for yield calculations",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rated_speed",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Rated speed in bottles per hour",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("8H_SHIFT_1", "8H Shift 1"),
                            ("8H_SHIFT_2", "8H Shift 2"),
                            ("8H_SHIFT_3", "8H Shift 3"),
                            ("12H_SHIFT_1", "12H Shift 1"),
                            ("12H_SHIFT_2", "12H Shift 2"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DowntimeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManufacturingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("order_date", models.DateField()),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of the product to be manufactured in packs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.packagesize",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturing Order",
                "verbose_name_plural": "Manufacturing Orders",
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="production_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="manufacturing.productionline",
            ),
        ),
        migrations.CreateModel(
            name="ProductionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_batch_number", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("production_start", models.DateTimeField()),
                ("production_end", models.DateTimeField(blank=True, null=True)),
                ("total_downtime_minutes", models.PositiveIntegerField(default=0)),
                (
                    "final_syrup_volume",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("mixing_ratio", models.CharField(max_length=50)),
                ("filler_output", models.DecimalField(decimal_places=2, max_digits=10)),
                ("good_products_pack", models.PositiveIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.manufacturingorder",
                    ),
                ),
                (
                    "package_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.packagesize",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.product",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.productionline",
                    ),
                ),
                (
                    "shift_teamleader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.shift",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("production_batch_number", "production_line", "date")
                },
            },
        ),
        migrations.CreateModel(
            name="ProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "syrup_yield_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "preform_yield_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bottle_reject_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "label_reject_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "shrink_wrap_reject",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shrink_wrap_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "co2_utilization_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "availability",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "performance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quality",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "oee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "production_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="manufacturing.productionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackagingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_preform_used", models.PositiveIntegerField()),
                ("qty_cap_used", models.PositiveIntegerField()),
                ("qty_product_reject", models.PositiveIntegerField()),
                ("qty_preform_reject", models.PositiveIntegerField()),
                ("qty_bottle_reject", models.PositiveIntegerField()),
                ("qty_cap_reject", models.PositiveIntegerField()),
                (
                    "label_reject_g",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "shrink_wrap_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stretch_wrap_g",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "production_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_material",
                        to="manufacturing.productionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StopEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "production_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_events",
                        to="manufacturing.productionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kg_co2", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "boiler_fuel_l",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "generator_fuel_l",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "edg_power_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "production_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility",
                        to="manufacturing.productionrun",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="machine",
            unique_together={("production_line", "machine_name")},
        ),
    ]
