# Generated by Django 5.2.6 on 2025-09-11 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionrun",
            name="target_quantity",
        ),
    ]
