# Generated by Django 5.2.6 on 2025-09-10 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stopevent",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="manufacturing.downtimecode",
            ),
        ),
        migrations.AlterField(
            model_name="stopevent",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manufacturing.machine"
            ),
        ),
    ]
