# Generated by Django 5.2.6 on 2025-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0002_remove_productionrun_target_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stopevent",
            name="reason",
            field=models.CharField(max_length=255),
        ),
    ]
