# Generated by Django 5.2.6 on 2025-09-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0003_alter_stopevent_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stopevent",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
