# Generated by Django 5.2.6 on 2025-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0004_alter_stopevent_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="main_machine",
            field=models.BooleanField(default=False),
        ),
    ]
