# Generated by Django 5.2.6 on 2025-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0005_machine_main_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagesize",
            name="bottle_per_pack",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
