# Generated by Django 5.2.6 on 2025-09-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0006_packagesize_bottle_per_pack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionrun",
            name="mixing_ratio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
