# Generated by Django 5.2.6 on 2025-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0007_alter_productionrun_mixing_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_can_cover_reject",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_can_cover_used",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_can_used",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_carton_reject",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_carton_used",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_empty_can_reject",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagingmaterial",
            name="qty_filled_can_reject",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
