# Generated by Django 5.2.6 on 2025-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0008_packagingmaterial_qty_can_cover_reject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downtimecode",
            name="code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="downtimecode",
            unique_together={("machine", "code")},
        ),
    ]
