# Generated by Django 5.2.6 on 2025-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0009_alter_downtimecode_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stopevent",
            name="is_planned",
            field=models.BooleanField(default=False),
        ),
    ]
