# Generated by Django 5.2.6 on 2025-10-04 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0010_stopevent_is_planned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagingmaterial",
            name="qty_filled_can_reject",
        ),
    ]
